from . import darslar_hendler
from . import help
from . import murojaga_javob
from . import elonlar
from . import elonlar_user
from . import murojat
from . import xodimlar_user
from . import xodimlar_hendler
from . import darslar_hendler_user
from . import bot_sozlamalari
from . import zamdekan_uchun
from . import start
from . import echo